name: Sewers
version: 0.20
description: Sewers in Minecraft!
load: STARTUP
authors: [hammale, Gyroninja]
main: me.hammale.Sewer.Sewer
commands:
    sewer:
        description: "Use this command to generate a sewer."
        usage: "Sewers 0.2 Pre-release commands: /sewer create"