name: Sewers
version: 0.3.0
description: Sewers in Minecraft!
load: STARTUP
authors: [hammale, Gyroninja]
main: me.hammale.Sewer.Sewer
commands:
    sewer:
        description: "Use this command to generate a sewer."
        usage: "Sewers 0.3.0 commands: /sewer create, /sewer locate"