name: Sewers
version: 0.20
description: Sewers in Minecraft!
load: STARTUP
authors: [Hammale, Gyroninja]
main: me.hammale.Sewer.Sewer
version: 0.20
commands:
    sewer:
        description: "Use this command to generate a sewer."
        usage: "Incorrect usage, try /sewer create"